### ISSUE TITLE
Receive unexpected "Close" event

### ISSUE THREAD

**Issue by Jnp95** [robtaussig/react-use-websocket#112]
Hello,

In the `shouldReconnect` callback, I receive a "Close" event every minute (code 1006). Whereas with others websocket clients, I don't.
Have you an idea ?

```
const webSocketContent = useWebSocket(url, {
      share: true,
      shouldReconnect: (e) => {
        console.log('shouldReconnect event:', e);
        return false;
      },
  });
```

**Comment by robtaussig** [comment]
Hi @Jnp95,

Could you please provide me an example of how/where you are using the hook? The `shouldReconnect` callback will be called whenever a WebSocket closes. Is it every minute on the dot?

**Comment by MaxBittker** [comment]
other websocket clients might be sending keepalive pings?  (?)

**Comment by Jnp95** [comment]
In fact, troubles was caused by websocket server. So this library is not in
fault anymore.

Le mer. 22 déc. 2021 à 01:36, Max Bittker ***@***.***> a
écrit :
