### ISSUE TITLE
getWebSocket().close() not closing 

### ISSUE THREAD

**Issue by MaxBittker** [robtaussig/react-use-websocket#118]
hi! Thanks for the nicely designed library, i've used it for a few projects.

I am trying really hard to get my websocket to close (and immediately reconnect) on demand. 

(idea being to trigger this behavior when I stop receiving "ping pong" heart beats from the server because it's crashed and rebooted. ) 

The issue I'm experiencing is that the methods I've tried to close the websocket don't seem to do anything. 

I've tried both `getWebSocket().close()` and passing `false` to the third parameter. 

 I am **not** passing `share: true`, which I understand change the behavior of these methods. 
 
 
 Do you have any advice of where to look? I tried to make a minimal reproduction [here](https://codesandbox.io/s/ws-reconnect-test-cw4hn?file=/src/Socket.js), but it actually works fine, so I am confused about what I might be doing wrong in my more complicated app 😅

**Comment by oliver1epic** [comment]
shouldReconnect: (_closeEvent) => {
      timer.start();
      console.error(_closeEvent);
      console.log("Reconnecting to the state server.");
      return false;
    }

**Comment by MaxBittker** [comment]
?

**Comment by robtaussig** [comment]
@MaxBittker I'll take a look at your example later to see if anything stands out as "almost" not right, but I'd be more likely to spot the issue if you were able to provide an example of where it isn't working.

**Comment by robtaussig** [comment]
Hi @MaxBittker 

I think a good place to start is here:

```tsx
  useEffect(() => {
    if (timedOut && readyState === 1) {
      console.log("Manually closing the state server socket due to a timeout.");
      getWebSocket().close();
      timer.start();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [getWebSocket, timer.start, timedOut]);
```

By not including `readyState` in the dependency array, you are possibly checking a stale value here: `readyState === 1`, and perhaps even when it times out, by the time it timed out, `readyState` was no longer `OPEN` (1).
Can you confirm whether `"Manually closing the state server socket due to a timeout."` is ever being logged to console?

It also might help to try a simpler approach so that it's easier to debug:

```tsx
export default function useSocketConnection() {
  const closeTimeout = useRef();

  const { sendJsonMessage, getWebSocket, readyState } = useWebSocket(WS_URL, {
    // Whenever a message is received, reset the close timeout
    onMessage: ({ data }) => {
      let message = JSON.parse(data);
      if (message.error) {
        console.error(message.error);
        return;
      }

      if (closeTimeout.current) clearTimeout(closeTimeout.current);
      closeTimeout.current = setTimeout(() => {
        if (getWebSocket().readyState === 1) {
          getWebSocket().close();
        }
      }, 6 * 1000);
    },
    // initiate timeout to close websocket on open event;
    onOpen: () => {
      // always clearTimeout if one exists on new connection
      if (closeTimeout.current) clearTimeout(closeTimeout.current);
      closeTimeout.current = setTimeout(() => {
        if (getWebSocket().readyState === 1) {
          getWebSocket().close();
        }
      }, 6 * 1000);
    },
    // Cancel timeout so that we don't attempt to close a closed websocket
    onClose: () => {
      if (closeTimeout.current) clearTimeout(closeTimeout.current);
    },
    // Always reconnect
    shouldReconnect: (_closeEvent) => {
      return true;
    }
  });

  // Only send 'PING' message when readyState is OPEN
  useEffect(() => {
    if (readyState === 1) {
      const interval = setInterval(() => {
        sendJsonMessage({ type: "PING" });
      }, 2 * 1000);

      return () => {
        clearInterval(interval);
      };
    }
    
  }, [readyState, sendJsonMessage]);

  return readyState;
};
```
