### ISSUE TITLE
websocket.onmessage  

### ISSUE THREAD

**Issue by liuxiaobina** [robtaussig/react-use-websocket#12]
Can the time consumed by the websocket.onmessage function be optimized? It feels like a bit of a performance impact, because there are many functions nested to execute.
![image](https://user-images.githubusercontent.com/27754478/64141228-cf6d1100-ce39-11e9-9e38-fae058607906.png)
Some cost 20 to 40 ms

**Comment by robtaussig** [comment]
@liuxiaobina, thank you for your feedback. I welcome all PRs and constructive critique, so feel free to disagree, but I don't think a library like this can do much better than that. The only two functions bound to websocketInstance.onmessage are an optional callback provided by you and the React.useState setter function, which is required to set the message state and update your component. The latter is what is responsible for the nested functions that you see in the performance profile (that or you are also providing a react state setter in the optional callback).

Thinking on this, I can see how 20-40ms might be too slow for things like multiplayer games where game state is synchronized by websocket, but if that is your use-case, you are probably best to minimize the abstraction layers on top of the communication protocol and instantiate and handle a single-purpose websocket.

That said, you can try the optional filter callback and always return false to prevent the hook from updating state, and then handle the message yourself with the onMessage callback. I would be curious if this improves performance in any noticeable way.

**Comment by robtaussig** [comment]
I'm going to close this issue, but feel free to continue the conversation!
