### ISSUE TITLE
CHANGELOG 🙏 

### ISSUE THREAD

**Issue by Semigradsky** [robtaussig/react-use-websocket#124]
Hi and thanks for a great library.
Could you please add the CHANGELOG file? Or fill https://github.com/robtaussig/react-use-websocket/releases
It is not very clear what breaking changes were introduced in v3.

**Comment by robtaussig** [comment]
Hi @Semigradsky,

Thank you for the kind words and for the great suggestion to fill out the release form. Let me know if I did this correctly:
https://github.com/robtaussig/react-use-websocket/releases/tag/3.0.0

To quickly address your question, there are no breaking changes in `3.0.0`.

**Comment by Semigradsky** [comment]
It looks great! Many thanks!
