### ISSUE TITLE
Allow typing response

### ISSUE THREAD

**Issue by DominicTobias** [robtaussig/react-use-websocket#125]
Hey, it seems like it's not possible to type `lastMessage`?

The definition is:

```ts
export declare const useWebSocket: (url: string | (() => string | Promise<string>) | null, options?: Options, connect?: boolean) => WebSocketHook;
```

So even though `WebSocketHook` accepts a generic, we are unable to pass one through from `useWebSocket` due to it not accepting one. Should it be like this?

```ts
export declare const useWebSocket: <T>(url: string | (() => string | Promise<string>) | null, options?: Options, connect?: boolean) => WebSocketHook<T>;
```

Is there another recommended way to type the response?

**Comment by robtaussig** [comment]
Sorry for the late delivery, and thank you for your patience @DominicTobias ,

Updated to 4.2.0!

https://github.com/robtaussig/react-use-websocket/commit/7f706878666f9ce28660e34c11d10728f96fe3b1

**Comment by DominicTobias** [comment]
Nice thanks @robtaussig
