### ISSUE TITLE
Handshake fails when using protocols option

### ISSUE THREAD

**Issue by CarolynWebster** [robtaussig/react-use-websocket#132]
I am trying to pass authorization information via the protocols option, and when I add them in, the handshake fails. I remove them, it all works fine.

I can properly see the auth info in my headers, so I know it is able to add it via protocols, and I can see the connect succeeding on the server side, so I think the server socket setup is fine. As soon as I comment out the protocols, the socket works, but is obviously not passing the needed auth info. Any ideas of what could be going on?

No helpful error messages in the console, it just fails to complete the handshake. Screenshot of the results of `onError` below

using `"react-use-websocket": "3.0.0"`

```
    const { sendJsonMessage } = useWebSocket(socketUrl, {
        share: true,
        protocols: ["Authorization", authToken], // authToken is a string
        onError: (e) => {
            console.log("error", e)
        },
        onOpen: () => {
            // now that we're connected, we need to subscribe the user to relevant channel(s)
            sendJsonMessage({
                message: "Connection Opened",
                type: "add.to.channels",
            })
        },
        onMessage: e => {
            // message code here
        },
        shouldReconnect: () => true,
    })
```

I tried using `onError` to get some info on what was going on, but didn't see much there to help

![Screen Shot 2022-03-31 at 9 27 44 AM](https://user-images.githubusercontent.com/24425741/161104520-8cff7ae8-5e0d-43be-8969-ddfe6e65cf43.png)

**Comment by CarolynWebster** [comment]
Turns out my issue was related to the server not returning a matching subprotocol - https://stackoverflow.com/questions/70250073/websockets-to-localhost-fails-in-chromium-based-browsers

**Comment by imtmh** [comment]
I got the same issue, It used to work fine without protocol error. After adding authorizer for Websocket and sending the auth tocken in protocol, Its not working. But its working fine via terminal when I fire websocket using wscat. Help appreciated.
