### ISSUE TITLE
React 18 - Batching breaks react-use-websocket

### ISSUE THREAD

**Issue by tomisu** [robtaussig/react-use-websocket#135]
I updated React to v18, which includes state batching. This brought some issues to react-use-websocket.

If the websocket gets 2 messages very close in time, one of them will be skipped, since the `setLastMessage` calls are being batched.

This should be avoided including `flushSync` whenever setting these state variables.

Thanks!

**Comment by robtaussig** [comment]
Thank you @tomisu for bringing this to my attention! I will definitely prioritize this fix.

**Comment by robtaussig** [comment]
Hi @tomisu ,

Here's the commit: b52c5f907526074ed19c83bac4e61a7422bf1969

I updated the peerDependencies to 18 and published to a new major version (`4.0.0`), and wrapped the state setters in `flushSync`. I don't have any complex projects at the moment using react 18, so please let me know if this solves your problem!

**Comment by tomisu** [comment]
Hello @robtaussig

I updated to `4.0.0`, and it works perfectly with React 18. My project isn't that big, but it seems like the issue is resolved.

Thanks a lot for such quick update!

**Comment by robtaussig** [comment]
You're welcome! And thanks again for reporting this.
