### ISSUE TITLE
Add an option to skip isWebSocket check

### ISSUE THREAD

**Issue by zerofirework** [robtaussig/react-use-websocket#139]
Hi dev team,

I'm writing cypress tests that mock websocket messages. I'm using mock-socket library that creates a mock type of web socket instance. It conflicts with the `assertIsWebSocket` function in the react-use-websocket because it is not an instance of the native WebSocket.

Can we add a new option to skip this check? For example:

```
const { sendMessage, lastMessage, readyState } = useWebSocket(socketUrl, {
  skipAssert: true
});
```

**Comment by robtaussig** [comment]
Hi @zerofirework 

Updated to 4.1.3.

Thanks for the suggestion!

https://github.com/robtaussig/react-use-websocket/commit/e7c10efb315a4802896790d8e5a437a4f58466c9

**Comment by zerofirework** [comment]
Thanks for the quick implementation!

**Comment by zerofirework** [comment]
BTW, is there any chance that this change can be ported back to 3.0.0?

**Comment by Yama-Tomo** [comment]
@robtaussig I would like to see this feature ported to 3.0.0 as well!
