### ISSUE TITLE
Not hardcoding query params for socket-io handshake

### ISSUE THREAD

**Issue by eric-blue** [robtaussig/react-use-websocket#14]
https://github.com/robtaussig/react-use-websocket/blob/99d29db3e42952cebab8805bddd9868eb2e94aa0/src/lib/socket-io.ts#L20

a lib like [socket.io-client](url) provides an additional `query` object when performing the handshake. This allows the client to pass alongside `transports: "websocket"` additional params such as `user_id: 9000` that the socket.io backend can consume.

Might it make sense to pass these along the options in the `useSocketIo` hook instead of hardcoding them into the `SOCKET_IO_PATH` constant?

**Comment by robtaussig** [comment]
I like it. If you define a queryParam object in options, it will be stringified and appended to the final url. Thanks for the suggestion! Updated README.

20bc77211710ff6aee853caf69f0cdafeaaab4f7
