### ISSUE TITLE
lastMessage undefined if not named 'lastMessage'

### ISSUE THREAD

**Issue by SaremS** [robtaussig/react-use-websocket#149]
Hi, 

is this intended:

`const { sendMessage, lastMessage, readyState } = useWebSocket(socketUrl);`

is working fine, but 

`const { sendMessage2, lastMessage2, readyState2 } = useWebSocket(socketUrl);`

results in `lastMessage2===undefined`

Thanks!

**Comment by koralarts** [comment]
This is expected. `useWebSocket` returns an object  -- see [doc](https://www.npmjs.com/package/react-use-websocket). You are destructuring that object whenever you write `const { sendMessage, lastMessage, readyState } = useWebSocket(socketUrl);`. This means the names within the `{}` are keys that exist in the returned object. You can rename those in your destructure by `{ sendMessage: sendMessage2 }`.

More Info:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring

**Comment by robtaussig** [comment]
Thanks @koralarts
