### ISSUE TITLE
Block-scoped window redeclaration not allowed

### ISSUE THREAD

**Issue by eric-blue** [robtaussig/react-use-websocket#15]
Current implementation of the globally declared `const window: { ... }` throws error in compiler

```
ERROR in .../node_modules/react-use-websocket/dist/lib/socket-io.d.ts(3,11):
TS2451: Cannot redeclare block-scoped variable 'window'.
ERROR in .../node_modules/typescript/lib/lib.dom.d.ts(18212,13):
TS2451: Cannot redeclare block-scoped variable 'window'.
```

caused by:
```
declare global {
    const window: {
        location: {
            protocol: string;
            port: number;
            hostname: string;
        };
    };
}
```
Simply removing the offending declaration allows it to compile, but I am unaware as to what use-case keeping it solves.

Alternatively, adjusting it to an interface resolves the compilation as well:

```
declare global {
    interface Window {
        location: Location;
    }
}
```

**Comment by robtaussig** [comment]
Thank you for the heads up! Will fix tonight.

- Sent from mobile. Please forgive brevity.

**Comment by robtaussig** [comment]
It began as what I thought would be a simple fix (add 'dom' to the tsconfig library list), and then became a mini project overhauling the library types. Let me know how it looks!

ffe13ffb7a0fc36a8607d259a6b58270ec19f7e5

**Comment by alekhrycaiko** [comment]
Those look like nice improvements. Thanks for the efforts @robtaussig !

**Comment by eric-blue** [comment]
> It began as what I thought would be a simple fix (add 'dom' to the tsconfig library list), and then became a mini project overhauling the library types. Let me know how it looks!

@robtaussig works great, thanks for the quick turnaround!
