### ISSUE TITLE
Creating a new instance of websocket when opening new browser tab

### ISSUE THREAD

**Issue by cjambrosi** [robtaussig/react-use-websocket#155]
Hello!
Is possible not to create a new websocket instance when opening a new browser tab?

**Comment by cjambrosi** [comment]
I'm using version 3.0.0, at the moment

**Comment by robtaussig** [comment]
Do you mean to share a single websocket across multiple browser tabs? You might be able to achieve something like this using `IndexDB` and https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/complete_event to listen for new entries across browser tabs, and leverage this to coordinate multiple instances of your app to open only one websocket and share its messages, but this would be way beyond the scope of this library.
