### ISSUE TITLE
Getting type errors on `lastJsonMessage`

### ISSUE THREAD

**Issue by ps2-controller** [robtaussig/react-use-websocket#156]
Hi! I suspect this comes from a lack of understanding on my part, but I'm getting type errors in my codebase whenever I use `lastJsonMessage` --> Here's a simple example, and how it's affecting me:

```
  const { lastJsonMessage, readyState } = useWebSocket(socket_url)
  console.log(lastJsonMessage?.some_var)
```
^ Typescript doesn't like this for the following reason:

```
Property 'some_var' does not exist on type 'JsonValue'.
  Property 'some_var' does not exist on type 'JsonArray'.
```

------
Looking into the Type it expects for lastJsonMessage to be of type T, defined in react-use-websocket as:
```
export declare type WebSocketHook<T = JsonValue, P = WebSocketEventMap['message'] | null> = {
    sendMessage: SendMessage;
    sendJsonMessage: SendJsonMessage;
    lastMessage: P;
    lastJsonMessage: T;
    readyState: ReadyState;
    getWebSocket: () => (WebSocketLike | null);
};
```

where JsonValue is defined as:
```
export declare type JsonObject = {
    [Key in string]?: JsonValue | JsonPrimitive;
};
/**
Matches a JSON array.
@category JSON
*/
export declare type JsonArray = JsonValue[];
/**
Matches any valid JSON value.
@see `Jsonify` if you need to transform a type to one that is assignable to `JsonValue`.
@category JSON
*/
export declare type JsonValue = JsonObject | JsonArray;
```
------

^^Looking at that, I'd expect Typescript to be happy with any JSON object sent as a message by the websocket

On the back-end, my websocket sends a message to the client structured as
```
{
   some_var: "foo",
   some_other_var: "bar"
}
```

The code correctly reads the `lastJsonMessage` variable and logs `some_var` if I `//@ts-ignore` the error

**Comment by ps2-controller** [comment]
This is my current workaround:
```
  const { sendJsonMessage: send_json_message, lastJsonMessage, readyState } = useWebSocket(socket_url, {
    queryParams: {
      token: lichess_token,
      connection_type: 'REVIEWER',
      stage: 'WAITING_FOR_MATCH',
    }
  });
  const last_json_message: any = lastJsonMessage // workaround for this issue: https://github.com/robtaussig/react-use-websocket/issues/156
```

**Comment by ps2-controller** [comment]
This is my current workaround:
```
  const { sendJsonMessage: send_json_message, lastJsonMessage, readyState } = useWebSocket(socket_url);
  const last_json_message: any = lastJsonMessage // workaround for this issue: https://github.com/robtaussig/react-use-websocket/issues/156
```

**Comment by robtaussig** [comment]
Hi @ps2-controller! Sorry for the late reply.

`useWebSocket` is a generic which means you can define type `T` in your code:

```
type ExpectedJsonMessage = {
  some_var: string;
  some_other_var: string;
};

const { sendJsonMessage: send_json_message, lastJsonMessage, readyState } = useWebSocket<ExpectedJsonMessage>(socket_url);

const result = lastJsonMessage.some_var; //ok
const result2 = lastJsonMessage.unexpected_var; //not ok
```
Alternatively, if you have no idea what kind of messages you might receive, or otherwise just want to get along with coding and not setting up your types, you can achieve what you did above more efficiently with:

```
const { sendJsonMessage: send_json_message, lastJsonMessage, readyState } = useWebSocket<any>(socket_url);

//Now you can access any properties on lastJsonMessage without TypeScript complaining
```

**Comment by Misiu** [comment]
@robtaussig I just had a similar issue and found your answer. Thank you :)
A quick question: what about sendJsonMessage?
if we use the generic version of `useWebSocket` we get a typed lastJsonMessage, but what do you think about adding a generic `sendJsonMessage`?

Now I do this:
```
const sendEventHandler = useCallback(() => {
  const message: IMessage = {
    type: "say",
    data: { first_part: "hello", second_part: "world" }
  };
  sendJsonMessage(message);
}, [sendJsonMessage]);
```

but ideally, I should be able to do this:
```
const sendEventHandler = useCallback(() => {
  sendJsonMessage<IMessage>({
    type: "say",
    data: { first_part: "hello", second_part: "world" }
  });
}, [sendJsonMessage]);
```

Idea is to have my custom type as the first argument and have code completion.

Sadly I'm new to TypeScript so I think I won't be able to send PR with this change and I'm not sure if there is an easy way to implement this.
I can create a new issue with this if needed.

**Comment by ps2-controller** [comment]
@robtaussig -- sorry totally missed your response way back when; landed on a similar conclusion. 

Just replying now to say thank you :) Your library is extremely appreciated!
