### ISSUE TITLE
Set binaryType 

### ISSUE THREAD

**Issue by AmazingTurtle** [robtaussig/react-use-websocket#16]
It is not possible to set binaryType for a websocket object.
It would be good to have a feature that allows to set a value for this.

**Comment by robtaussig** [comment]
Great suggestion and apologies for the delay in response. I've been thinking of working on an option that gives a little direct access to the websocket (that in this case would allow you to set binaryType), but I'm also concerned about a case in which the websocket is being shared across multiple components and one mutates it in a way that breaks everything else.

Of course, I can also just accept an option to set the binaryType when creating the websocket, and if it's a shared websocket, an error will be thrown if future subscribers try to set it to a binaryType other than what the original is. I'll think about it tonight and let you know!

**Comment by robtaussig** [comment]
@AmazingTurtle 

I put together a branch that I think will accomplish this. An example of the API/functionality can be seen here:

https://github.com/robtaussig/react-use-websocket/blob/socket_proxy/README.md#getwebsocket-function---proxy

What do you think?

**Comment by robtaussig** [comment]
I'm going to go ahead and close this thread and promote this change.
