### ISSUE TITLE
How to deal with non JSON messages?

### ISSUE THREAD

**Issue by phirestalker** [robtaussig/react-use-websocket#175]
This is the server code I am stuck with.
```
const webSocketServer = require('websocket').server;
const http = require('http');

const server = http.createServer();
server.listen(55455, '0.0.0.0');
const wsServer = new webSocketServer({ httpServer: server });

wsServer.on('request', function (request) {
    console.log('establishing a new connection with client');
    var connection = request.accept(null, request.origin);
    setInterval(() => {
        connection.sendUTF(new Date().getTime())
    }, 100);
});
```

Here is my current client code.

```
import React, { useState } from 'react';
import useWebSocket, { ReadyState } from 'react-use-websocket';
import './Latency.css'

export default function Latency() {
    // const [currentLatency, setCurrentLatency] = useState('');
    
    const { sendMessage, lastMessage, readyState, getWebSocket } = useWebSocket('ws://localhost:55455');

    const connectionStatus = {
        [ReadyState.CONNECTING]: 'Connecting',
        [ReadyState.OPEN]: 'Open',
        [ReadyState.CLOSING]: 'Closing',
        [ReadyState.CLOSED]: 'Closed',
        [ReadyState.UNINSTANTIATED]: 'Uninstantiated',
    }[readyState];

    // console.log(lastMessage)
    
    

    return (
        <span className='Exhibit-item'>{(lastMessage ? lastMessage.data : "no messages" + connectionStatus)}</span>
    )
}
```

The browser console is giving me an error.

> Uncaught SyntaxError: Unexpected token 'o', "[object Blob]" is not valid JSON
>   at JSON.parse (<anonymous>)
>   at socket.js:57:1
>   at client.onmessage (WebSocketClient.js:50:1)

How can I turn off JSON parsing of incoming messages?

**Comment by robtaussig** [comment]
Hmm, this is a bit strange. The only time `JSON.parse` would be called on the websocket message is here:

```tsx
const lastJsonMessage: T = useMemo(() => {
    if (lastMessage) {
      try {
        return JSON.parse(lastMessage.data);
      } catch (e) {
        return UNPARSABLE_JSON_OBJECT;
      }
    }
    return null; 
  },[lastMessage]);
```

Given that it's within a try/catch itself, no error should bubble up. I'll take a further look, but one thing you can try is to use the `filter` option which will pass along any incoming messages -- if you return `false` from it, that message will be ignore and should not cause any down-stream issues.

**Comment by phirestalker** [comment]
I have tried multiple client libraries, so it isn't this library. I think it is code-server proxy mangling the websocket somehow. Not sure how to find out.

I will close this, since it is not a bug in your library.
