### ISSUE TITLE
Feature: Exponential Backoff for Reconnect Attempts

### ISSUE THREAD

**Issue by gnoulk** [robtaussig/react-use-websocket#177]
Firstly, thank you for this amazing lib. It makes using websockets much quicker!

Currently, we are able to auto-reconnect with `shouldReconnect` and define the reconnect frequency with `reconnectInterval` and max attempts with `reconnectAttempts`. This would be greatly improved if we could use [Exponential Backoff](https://en.wikipedia.org/wiki/Exponential_backoff) on our reconnect attempts. This would allow our client to attempt reconnecting quicker during errors while not flooding the server with requests.

**Comment by sabrinaaah** [comment]
Thank you so much! I was just looking for something like this. This is super helpful!
