### ISSUE TITLE
How to sendMessage once connection established?

### ISSUE THREAD

**Issue by loganx510** [robtaussig/react-use-websocket#18]
It is not really clear how to do that now. I suppose you can call sendMessage in the options object. But is it better way ? Thanks

**Comment by robtaussig** [comment]
@loganx510

For a chat application that I've used this for, where I wanted a message sent to the server indication that a user has connected, I created a useEffect with readyState as the dependency. Inside of the useEffect, I would check if readyState is equal to 1 (i.e., 'open'), and if so I would send the message using the callback provided by the hook. This should only ever happen once unless the socket disconnects and you have set the options to reconnect on disconnect. Which, if so, you probably want the message to be sent again anyway.

The nice part about the above pattern is that you can return a function from within the if block that handles disconnection (won't be able to send a message from the socket, obviously, but you can display something in the UI, etc)

**Comment by loganx510** [comment]
Thank you for the detailed answer. It works) 
`useEffect(() => {
    if (readyState === 1) {
      sendMessage()
    }
  }, [readyState])`

**Comment by robtaussig** [comment]
Glad to hear it!
