### ISSUE TITLE
how can I passing username and password for my mqtt broker

### ISSUE THREAD

**Issue by filmfuthoem** [robtaussig/react-use-websocket#19]
Hi there,

I'm trying to use the library connect to my mqtt broker but I can't find an option to send credential for my mqtt broker.

Any idea?

**Comment by robtaussig** [comment]
Hi @filmfuthoem,

I don't have any experience working with mqtt broker, but if you could explain how you might do this with a vanilla WebSocket, I can either suggest a way to do so with the current API, or propose a solution for a future release. A quick search for WebSocket authentication led me to [this](https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api). Based on the following example:

`var ws = new WebSocket("ws://username:password@example.com/service");`

It looks like username:password would be part of the websocket url that you pass to useWebSocket. Let me know if this doesn't work for your use-case.

**Comment by robtaussig** [comment]
Alternatively, you can set the cookie, which will be received server-side:

```js
var authToken = 'R3YKZFKBVi';

document.cookie = 'X-Authorization=' + authToken + '; path=/';

var ws = new WebSocket(
    'wss://localhost:9000/wss/'
);
```

**Comment by robtaussig** [comment]
I'm going to close this issue, as authentication is beyond the scope of this library.
