### ISSUE TITLE
Send message on connection

### ISSUE THREAD

**Issue by JonSilver** [robtaussig/react-use-websocket#2]
Nice idea for a custom hook! Thanks for sharing!

In my use-case, my component must send a message in the onOpen event in order to register the filter criteria for its subscription. So far I've not been able to work out a way to do this because the onOpen event handler must be registered using the options at the time of useWebSocket creation, at which point the sendMessage function doesn't yet exist. Any ideas? :)

**Comment by robtaussig** [comment]
Sounds like you want to feed the chicken the egg!

Kidding aside, I think you should be able to add a useEffect hook after useWebsocket with the readyState as the memoized dependency. And in the closure, call send message only when the readyState is 1
