### ISSUE TITLE
Compatibility issue on JsonValue

### ISSUE THREAD

**Issue by nikitawolfik** [robtaussig/react-use-websocket#201]
version: 4.3.1

I have a specific shape for ws responses, let's keep a simple example of

```
export interface ChatResponseBusy {
  busy: boolean;
  type?: "busy";
}

But then trying to pass this type as a generic to `useWebSocket` as in `useWebSocket<ChatResponseBusy>(args)` throws ts error that it expects an index signature instead of specifically typed object. My types are also kind of immutable being generated based on type definitions provided by backend.

Is there any way to properly type the response without some hacks that would defeat the purpose of auto-generating types?

**Comment by robtaussig** [comment]
Apologies for the late reply. I'm surprised by this; I wonder if the previous implementation worked under an earlier version of TypeScript? I updated the generic to accept any arbitrary type: dc320d4

Released to [4.4.0](https://www.npmjs.com/package/react-use-websocket/v/4.4.0)
