### ISSUE TITLE
About "Static Options"

### ISSUE THREAD

**Issue by StinsonZhao** [robtaussig/react-use-websocket#21]
Why not try to implement "Options" as "Init Value," just like "useState" handles its argument.

Then if options change when rerendering, the changed options will be ignored. If so, we can remove that exception "The options object you pass must be static"

**Comment by robtaussig** [comment]
Thanks for the suggestion @StinsonZhao 

That would definitely work insofar that the error would never be thrown, but I also want to make sure that users are aware of the fact that any changes to options will be ignored (hence throwing the error), especially when it comes to closures. My biggest concern is something like this:

```tsx
//In Component.tsx

const Component = () => {
  const [count, setCount] = useState<number>(1);

  //Messages we send are echoed back
  const onMessage = (messageEvent: WebSocketEventMap['message']) => {
    console.log(messageEvent.data);
    console.log(count);
  };

  const [sendMessage, lastMessage, readyState] = useWebSocket('wss://echo.websocket.org', {
    onMessage,
  });

  const handleClick = () =>  setCount(prev => prev + 1);

  useEffect(() => readyState === 1 && sendMessage(count), [readyState, count]);

  return (<button onClick={handleClick}>Increment</button>);
}

/*
  Event log
  1. Once readyState is 'open', useEffect is executed, invoking sendMessage with count of 1
  2. messageEvent.data is logged (1)
  3. count is logged (1)
  4. User clicks button, increments count by 1
  5. useEffect is executed, sendMessage with count of 2
  6. messageEvent.data is logged (2)
  7. count is logged (1)
  8. Repeat above 4 steps, and messageEvent.data will always increment by 1, but count will always be static
*/
```

It's the kind of bug that generally won't be immediately obvious, but results in very strange, hard-to-debug behavior. There are workarounds available (one being to keep count in a ref that onMessage uses), but a user would only think about trying a workaround if he or she is aware of the fact that Options is read only once. If it weren't for the fact that the library aims to support 'sharable' web sockets, it would be easy enough to just rebind the websocket.onmessage handler every time the options reference changes, but with shareable websockets, it is more complicated. I've considered allowing for dynamic options if the share property isn't true, but another philosophy I'm aiming to support is that changing it between true/false only effects whether multiple web sockets will be opened -- nothing should change with the API.

**Comment by theredwillow** [comment]
@robtaussig I keep getting this error message every time I try to use options, even an empty object. Is there a bug happening?

```
const [socketUrl, setSocketUrl] = useState<string>(`wss://${window.location.host}/api/ws`);

// EXAMPLE THAT WORKS
const [sendMessage, _, readyState] = useWebSocket(socketUrl);

// EXAMPLE THAT DOESN'T
const [sendMessage, _, readyState] = useWebSocket(socketUrl, { }); // THROWS ERROR

```

Maybe I'm just not grasping a concept?
