### ISSUE TITLE
Return a "WillReconnect" boolean

### ISSUE THREAD

**Issue by msopacua** [robtaussig/react-use-websocket#210]
We can set a number of reconnect attempts, but the parent component has no way of knowing, if a reconnect attempt will be made or if we passed our quota.

My use case is that I send chunks of data over the socket to the backend for processing - pretty much background uploading via websocket. The application expects a message back once all chunks have been sent. If the socket is not open, we signal that the chunk has to be retried. If it's unreasonable to expect that the socket will be re-opened, I should abort the uploading but currently have no way to determine this and tracking `readyState` and creating my own reconnect counter is a) duplicate work that b) might go out of sync.

I realize there's a "keep" option on sendMessage, however I need to send chunks in order or the receiving end gets a broken file and the dequeuing in useWebsocket may send chunk 1, not 2 and requeue at the end and then send and dequeue 3.

**Comment by danielmcmillan** [comment]
There is the `onReconnectStop` callback which can be used for this.

**Comment by robtaussig** [comment]
I like @danielmcmillan's approach here. I did not anticipate `onReconnectStop` to be used for something like this, but I believe @danielmcmillan's approach should achieve your goal (as well as allowing you to implement a recovery workflow where resetting `connect` to `true` should completely reinstantiate the websocket and reset the retry counters, etc)
