### ISSUE TITLE
Expose readyState constants enum

### ISSUE THREAD

**Issue by kaa** [robtaussig/react-use-websocket#23]
May I suggest exporting the ready state constants from the library. That would keep everyone from having to redefine them for themselves.

Similar to the following,

```javascript
import { useWebSocket, ReadyState } from 'react-use-websocket';

if(readyState===ReadyState.CONNECTING) {
  ...
}
```

**Comment by robtaussig** [comment]
Good suggestion. I'll include this in the next update. Thanks!

**Comment by robtaussig** [comment]
Just pushed the commit and bumped npm version. Thanks again!

7e5fe12
