### ISSUE TITLE
Does the websocket disconnect on unmount?

### ISSUE THREAD

**Issue by yubinjodev** [robtaussig/react-use-websocket#230]
In the features section of the readme, it does say the following but is confusing:

> Multiple components can (optionally) use a single WebSocket, which is closed and cleaned up when all subscribed components have unsubscribed/unmounted

What I want to know for sure is that the websocket connection is disconnected when the component with the connection is unmounted.

**Comment by robtaussig** [comment]
@yubinjodev 

if you use the option to share a websocket, then only one websocket will be created, even if multiple components are using it. In this case, it will only close once all components (with the share option) unmount. If you are not using the share option, then the websocket is bound to the lifecycle of that component and will close once the component unmounts

**Comment by RELNO** [comment]
@robtaussig thanks - can you please elaborate how sharing looks like? 
Say we have 2 comps, `Test` and `TestNest`

```
import useWebSocket from "react-use-websocket";
import TestNest from "./TestNest";

const Test = () => {
  useWebSocket("wss://__URL__", {
    share: true,
    shouldReconnect: () => true,
  });

  return <TestNest />;
};

export default Test;
```
Should `TestNest` connect again even if the WS tunnel is already opened and shared? i.e

```
const TestNest = () => {
  const { readyState, sendJsonMessage, lastJsonMessage } = useWebSocket(
    "wss://__URL__"
  );
  ...
  ```

**Comment by robtaussig** [comment]
In your example, TestNest will open its own WebSocket because it is not using the share option.

**Comment by RELNO** [comment]
Thanks - to verify, the syntax in the children has to practically match the parent for sharing to take place? 
```
useWebSocket("wss://__URL__", {
    share: true,
    shouldReconnect: () => true,
  });
```

**Comment by robtaussig** [comment]
Sort of. The only hard requirement is that they have the `share` property set as `true`. Some options can be different (such as `filter`, onMessage, etc), whereas others _should_ be identical, like those that deal with reconnecting — in reality, if these options are not the same between components, then the likely result will be that the component that established the connection first will dictate the options.

And not to be pedantic, but sharing a websocket isn’t necessarily limited to parent-child components. Imagine an app with a stock ticker component. It would be nice if it can be dropped anywhere in your app and “just work”, but you wouldn’t want every component to open a new websocket, and you wouldn’t want them to have to be aware of each other — this was the primary goal of mine when designing the share option.

**Comment by RELNO** [comment]
@robtaussig thanks for elaborating, makes total sense. I don't know how much of a refactoring/redesign this might require, but I imaging that a _global_-like object that is accessible from all components could simplify the sharing concept -- something along the lines of [usecontext](https://react.dev/reference/react/useContext)

**Comment by robtaussig** [comment]
@RELNO appreciate the feedback!
