### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by praveen08022002** [robtaussig/react-use-websocket#253]
#11 25.77 import { useWebSocket } from './lib/use-websocket';
#11 25.77 ^^^^^^
#11 25.77
#11 25.77 SyntaxError: Cannot use import statement outside a module
#11 25.77  at Object.compileFunction (node:vm:360:18)
#11 25.77  at wrapSafe (node:internal/modules/cjs/loader:1126:15)
#11 25.77  at Module._compile (node:internal/modules/cjs/loader:1162:27)
#11 25.77  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
#11 25.77  at Module.load (node:internal/modules/cjs/loader:1076:32)
#11 25.77  at Function.Module._load (node:internal/modules/cjs/loader:911:12)
#11 25.77  at Module.require (node:internal/modules/cjs/loader:1100:19)
#11 25.77  at require (node:internal/modules/cjs/helpers:119:18)
#11 25.77  at Object.7636 (/home/***/services/gst-self-serve/.next/server/pages/[token].js:11846:18)
#11 25.77  at __webpack_require__ (/home/***/services/gst-self-serve/.next/server/webpack-runtime.js:25:42)
#11 25.77
#11 25.77 > Build error occurred
#11 25.78 Error: Failed to collect page data for /[token]
#11 25.78  at /home/***/services/gst-self-serve/node_modules/next/dist/build/utils.js:1055:15 {
#11 25.78 type: 'Error'
#11 25.78 }

**Comment by csvan** [comment]
This is due to a breaking change which was introduced in 4.11

https://github.com/robtaussig/react-use-websocket/pull/249
