### ISSUE TITLE
Include types

### ISSUE THREAD

**Issue by onionhammer** [robtaussig/react-use-websocket#3]
Suggestion; it would be great to have types (.d.ts) for this library

**Comment by robtaussig** [comment]
Thanks for the suggestion!

**Comment by robtaussig** [comment]
Requires a little experimentation as I only have basic experience with TypeScript, but let me know if this looks right and I'll close the issue:

9c250f2187a475cabed47f83e9f0124196111159

**Comment by onionhammer** [comment]
I havent had a chance to try it out myself, but it seems correct from eyeballing it

**Comment by robtaussig** [comment]
Great! Thanks for your quick reply.
