### ISSUE TITLE
Problem with order of return values

### ISSUE THREAD

**Issue by carlospavanetti** [robtaussig/react-use-websocket#30]
See #7 
This hook has many return values to remember the right order. A object would be more appropriate, reducing the coupling between the return values and the hook usage.

**Comment by robtaussig** [comment]
Hi Carlos,

Thank you for your feedback. I am considering options for improving the api, but worry about making a breaking change as current use depends on the return value being an array. I have a few other issues I want to fix first, but when I can, I'll look into merging your PR for a major release (2.0).
