### ISSUE TITLE
Bug: does not reconnect when using a shared WebSocket

### ISSUE THREAD

**Issue by alxrocha** [robtaussig/react-use-websocket#34]
Version: 1.3.4

When using a shared WebSocket connection, once the connection closes, no reconnection is attempted.

```javascript
function WebSocket() {
  const options = useMemo(() =>({
    share: true,
    shouldReconnect: (closeEvent) => true,
    reconnectAttempts: 10,
    reconnectInterval: 3000,
  }, []);

  const [sendMessage, lastMessage, readyState] = useWebSocket('wss://echo.websocket.org', options);

  const status = {
    0: 'CONNECTING', 1: 'OPEN', 2: 'CLOSING', 3: 'CLOSED',
  }[readyState];

  return <span>WebSocket status: {status}</span>
}

function App() {
  return (
    <React.Fragment>
      <WebSocket />
      <WebSocket />
    </React.Fragment>
  );
}
```

## The current behaviour
No reconnection is attempted - the connection stays closed.

## The expected behaviour
The WebSocket should attempt reconnection. This works as expected when `share` is false.

**Comment by robtaussig** [comment]
Thanks @alxrocha ,

This indeed is a bug, and I'll prioritize fixing this asap.

**Comment by robtaussig** [comment]
Apologies for the delay. This was a bit trickier than I had anticipated, but I think I got it. Tested with a local server that I started and stopped intermittently, and shared websockets behaved correctly. I bumped version to 1.7.0.

Demo using your example: https://stackblitz.com/edit/react-prfxkc

ee7dd6b

Thanks for bug report!

**Comment by alxrocha** [comment]
No apologies needed.
Seems to be working properly, thank you so much for fixing the issue.

**Comment by pankajgupta1** [comment]
Hi this not again working in new version 2.0.1.
I am using shared websocket, but on unsubscription, when i again comes to a component in which I have used useWebSocket, then this not works. No connection occur.

**Comment by robtaussig** [comment]
Hi @pankajgupta1 ,

Could you please provide an example that I can look at to reproduce?

**Comment by robtaussig** [comment]
Hi @pankajgupta1,

I believe you hit the same (or similar) issue as reported here: #49.

To keep the conversation in one place, please check that thread! Thanks!
