### ISSUE TITLE
How to close socket

### ISSUE THREAD

**Issue by rootsli** [robtaussig/react-use-websocket#39]
`
const [sendMessage, lastMessage, getWebSocket] = useWebSocket(
    socketUrl,
    SOCKET_OPTIONS
  );

useEffect(() => {
    setTimeout(() => {
        getWebSocket().close();
      }, 3000);
  }, []);
`

browser console:
Uncaught TypeError:getWebSocket is not a function

**Comment by robtaussig** [comment]
Hi @rootsli,

The third item is readyState, which is an integer:) You need to do:

`
const [sendMessage, lastMessage, readyState, getWebSocket] = useWebSocket(
socketUrl,
SOCKET_OPTIONS
);

//or

const [sendMessage, lastMessage,, getWebSocket] = useWebSocket(
socketUrl,
SOCKET_OPTIONS
);
`
