### ISSUE TITLE
Close connection when unmounting component

### ISSUE THREAD

**Issue by dihdah** [robtaussig/react-use-websocket#4]
Hi! Thanks for the custom hook!

I was wondering if there is a way to close a websocket connection when unmounting component (navigating to a different view)?

**Comment by aaronr5** [comment]
The websocket connection should close when unmounting the component since there appears to be a cleanup function in this hook that changes the ready state to closing and closes the connection on unmount. However, someone can correct me if I am wrong about this.

**Comment by robtaussig** [comment]
Aaron's correct. The websocket will close on unmount unless the component
passes an options object to the hook with the property 'share' set to true.
This will, however, only prevent the websocket from closing on unmount if
there are still other components mounted and sharing that websocket. The
current implementation will close a shared websocket once all subscribed
components have unmounted.

I thought about taking an option to persist the websocket indefinitely, but
couldn't think of a situation where it wouldn't just be better to use the
hook in a parent component that never unmounts. Open to thoughts though!
