### ISSUE TITLE
allow passing `null` as `url`

### ISSUE THREAD

**Issue by ojii** [robtaussig/react-use-websocket#41]
`useWebSocket` checks for [`url !== null`](https://github.com/robtaussig/react-use-websocket/blob/e6cf259becd4803d6f9f62630d74521814bddcc2/src/lib/use-websocket.ts#L55) but it's [signature](https://github.com/robtaussig/react-use-websocket/blob/e6cf259becd4803d6f9f62630d74521814bddcc2/src/lib/use-websocket.ts#L15) does not allow urls to be null. 

Could the signature be changed to `string | (() => string | Promise<string>) | null` to match the implementation?

**Comment by robtaussig** [comment]
I actually really like this idea and am surprised I didn't think of it to begin with. It fixes two issues that I've thought about in the past -- cases in which the url may not be known at the beginning of the component lifecycle, and it provides an intuitive ('React'-) way to close the websocket. Will implement today.

**Comment by robtaussig** [comment]
Implemented!

7fdca5e
