### ISSUE TITLE
Add an option to immediately open the websocket connection (or not)

### ISSUE THREAD

**Issue by raphael-leger** [robtaussig/react-use-websocket#44]
It would be great to add an option to open the websocket by default. Or not open it by default.

For instance, I would like users to do a specific action  - let's say click on a button, before they connect to the websocket and start sending/receiving messages.

I do not want to open a websocket connection before users have clicked this button.
Sometimes they do not even click the button.

```js
  const STATIC_OPTIONS = useMemo(
    () => ({
      onOpen: () => console.log('socket opened'),
      connectImmediately: false, // default: true
    }),
    []
  );

  const [sendMessage, lastMessage, readyState, getWebSocket] = useWebSocket(
    config.WEBSOCKETS_URL,
    STATIC_OPTIONS
  );

  const onButtonClick = () => {
    getWebSocket().open();
  }
```

--

It would also be usable in a shared websocket, #43

**Comment by robtaussig** [comment]
Hi Raphael,

What are your thoughts on the implementation beloww?

```tsx
const [url, setUrl] = useState(null);

const STATIC_OPTIONS = useMemo(
    () => ({
      onOpen: () => console.log('socket opened'),
    }),
    []
);

const [sendMessage, lastMessage, readyState, getWebSocket] = useWebSocket(
    url,
    STATIC_OPTIONS
);

const onButtonClick = () => {
    setUrl(config.WEBSOCKETS_URL);
}
```

**Comment by raphael-leger** [comment]
@robtaussig, thank you for the quick and efficient answer.

As a first step, I think it could help to put a dedicated section into the README to show that setting and unsetting URLs actually means we have control over opening and closing a connection? For instance with the example you provided along with a sentence describing it.

As a second step, as I think it is not so obvious that we need to remove the url to close and re-add it to open, perhaps there could be a parameter given to `useWebSocket` specifying whether we would like the connection to be opened or not?

**Comment by robtaussig** [comment]
Hi @raphael-leger,

I agree with you that toggling the url is not an intuitive way to control the websocket, especially since it is fairly common to define your api urls as a constant. I like your suggestion to add a parameter that controls this. Will look into fitting this change into the next release.

**Comment by robtaussig** [comment]
@raphael-leger 

Implemented your suggestion to accept a param that controls whether the socket is open or closed (and toggles on change). Thank you for your patience and continued suggestions.

1110333

**Comment by qmg-rwaller** [comment]
hi @robtaussig, thanks for implementing this option, I've just used it 😄 would be great to see it doc'd in the README - I'd raise a PR but not sure where in the README is best to document this 3rd argument to the function

**Comment by robtaussig** [comment]
@qmg-rwaller

Good suggestion -- it's quazi-documented in the [New in V2](https://github.com/robtaussig/react-use-websocket#new-in-v2) section, but that section is both logically temporary and also not somewhere developers will typically look for actual documentation. I think something as basic as the parameters should likely be pretty high up in the README -- will add and update shortly:)

**Comment by robtaussig** [comment]
Added a section called [Interface](https://github.com/robtaussig/react-use-websocket#interface). Let me know if you have any thoughts!

**Comment by qmg-rwaller** [comment]
Ah yea I missed it in the New in V2 section, and should have checked the TypeScript. The new Interface section looks great, thanks!
