### ISSUE TITLE
Ease the use of json messages

### ISSUE THREAD

**Issue by raphael-leger** [robtaussig/react-use-websocket#45]
When dealing with websockets, it is common that messages are stringified objects.

Right now we can send such messages with the following:

```js
const message = {
    animal: 'cat',
    color: 'white'
};

sendMessage(JSON.stringify(message))
```

### Proposal A:
It would be handy to have a method that stringifies the given object directly without decreasing readability due to using `JSON.stringify`'s everywhere:

```js
const message = {
    animal: 'cat',
    color: 'white'
};

sendJsonMessage(message)
```

Something like `lastJsonMessage` could also be exposed with an object directly, instead of having to `JSON.parse()` everywhere

For instance, the library `Sockette` proposes [such a thing](https://github.com/lukeed/sockette#jsonobj).
Other example, the library `Socket.IO` even has this behavior of accepting an object by default through the method `socket.emit()`

### Proposal B
There could be a boolean option.
If set to true `sendMessage` will expect an object and `lastMessage` will be an object.
If set to false (*default* to introduce a non-breaking change), `sendMessage` will expect a string and `lastMessage` will be a string.

```
const STATIC_OPTIONS = useMemo(() => ({
  onOpen: () => console.log('opened'),
  messagesAreJsonObjects: => true
}), []);
```

**Comment by robtaussig** [comment]
Great suggestion. I'm actually currently working on the build that changes the return value to an object, where you can destructure the properties that your component needs. I will definitely add your first suggestion and include a jsonMessage and sendJsonMessage function. Thanks!

**Comment by robtaussig** [comment]
Just released v2, and incorporated Proposal A. Thank you for all of your suggestions!

1110333
