### ISSUE TITLE
Failed to construct URL from URL and Promise

### ISSUE THREAD

**Issue by ayooby** [robtaussig/react-use-websocket#48]
I tried to pass a function/promise, but it didn't work at all. 
I used the online demo, and also the error was still there.

```javascript
Error in /turbo_modules/react-use-websocket@1.1.0/dist/lib/create-or-join.js (12:47)
Failed to construct 'WebSocket': The URL 'function () {
return new Promise(function (resolve) {
setTimeout(function () {
resolve('wss://echo.websocket.org');
}, 2000);
});
}' is invalid.
```

can you please tell me what the problem is?

**Comment by robtaussig** [comment]
hi @ayooby!

Thank you for bringing this to my attention. The async url feature was introduced in a later version of the library than the one used in that demo. I updated the demo to use the latest version and tweaked the behavior of it to demonstrate the async url feature.
