### ISSUE TITLE
setLastMessage or clearLastMessage

### ISSUE THREAD

**Issue by watanabeshuji** [robtaussig/react-use-websocket#54]
I need `setLastMessage` or `clearLastMessage`.

I want to change parameter in url and reconnect.
So lastMessage at old param is not good.
It should be null.

So...
1. when url change, clear lastMessage
2. return clearLastMessage function at useWebSocket

**Comment by robtaussig** [comment]
I agree on both suggestions, and will implement.

**Comment by robtaussig** [comment]
Would you still need clearLastMessage if lastMessage gets cleared on reconnect (and if it reconnects correctly when url/queryParams change)?

**Comment by robtaussig** [comment]
In the meantime, lastMessage will be cleared in the cleanup function for reconenct behavior:

35445b0

**Comment by watanabeshuji** [comment]
No.
Automatically clear is enough to use, I think.

Thank you!

**Comment by robtaussig** [comment]
Great. I'll close this then.
