### ISSUE TITLE
How to manually close and reconnect a socket?

### ISSUE THREAD

**Issue by Artoria-0x04** [robtaussig/react-use-websocket#56]
In my situation, I need to temporarily close the connection and reconnect on the user's action. But native `close()` is protected and I don't find a method to reconnect a closed connection except for the built-in auto reconnecting.

**Comment by hoanglam10499** [comment]
@Artoria-0x04 
![Untitled](https://user-images.githubusercontent.com/37326429/91305284-07046400-e7d5-11ea-89a7-b208f26d9c6c.png)

**Comment by eric-blue** [comment]
close?

**Comment by robtaussig** [comment]
Thank you @hoanglam10499. Closed.

**Comment by Artoria-0x04** [comment]
Thanks, I haven't noticed that and temporarily reject the async `getSocketUrl` instead.
