### ISSUE TITLE
Reconnects leaking sockets?

### ISSUE THREAD

**Issue by caprica** [robtaussig/react-use-websocket#57]
I am testing this library and how it handles reconnects. I'm using a slightly modified version of the example application from the project README.

On the face of it, the reconnects appear to work just fine, I see the socket state going to closed when I kill my server then back to open after my server restarts, and the subsequent messages are delivered properly.

However, I am concerned about what I see in the Chrome DevTools Network tab:

![image](https://user-images.githubusercontent.com/1385879/91606080-5da2a700-e969-11ea-823b-5acd8958ce20.png)

Each time I restart my server I see a new socket created, but an old one appears to hang around.

The ones that are "Finished" in that screenshot are the ones where the 5 second timeout between retries failed to reconnect.

**Comment by robtaussig** [comment]
Hi @caprica 

I'm not familiar with how devtools tracks the Status, but I have only seen 'Finished' for websockets that never opened to begin with. If you attempt the following in console:

const a = {};
a.b = new WebSocket(/*websocket url*/');
a.b.onopen = () => {
    a.b.close();
    delete a.b;
}

You will see that the websocket closes based on the 'Time' column, but the Status will never change to 'Finished'.

**Comment by robtaussig** [comment]
And if you are not referring to the status column, but instead the fact that there are multiple websockets, it's because you have to create a new websocket in order to reconnect.

**Comment by caprica** [comment]
It was the status I was referring to, because some of them went to "Finished" I expected them all to.

But your explanation makes sense and this issue is just me misinterpreting what the DevTools are showing me.

Thank you.
