### ISSUE TITLE
How to Handle sendMessage error response?

### ISSUE THREAD

**Issue by jericopulvera** [robtaussig/react-use-websocket#59]
Hi, 

I'm trying to validate a JWT token in the server side and when returning a 401 response how do I handle it at the frontend?

```
      sendMessage(
        JSON.stringify({
          text: event.target.value,
          token
        })
      );
```

What I've tried so far.

```
 const { sendMessage, lastMessage, readyState } = useWebSocket(
    "ws://localhost:3333",
    {
      reconnectAttempts: 10,
      reconnectInterval: 3000,
      onError: (error) => {
        console.log(error);
      },
    }
  );
```

Did not log the error.

**Comment by robtaussig** [comment]
I apologize for the late reply. To be perfectly honest, I don't have a lot of experience with communicating errors via websockets, but my understanding is that if you want to trigger the onerror method of the websocket, the server will need close the connection with an 'abnormal' status code. See [here](https://tools.ietf.org/html/rfc6455#section-7.4.1).

Regarding your intended use-case, [this](https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api) looks like a promising lead. My gut tells me that you should not be handling authentication on the sendMessage action, but instead during the initial handshake.

I will leave this open for the time-being in case someone else might be more helpful.

**Comment by jericopulvera** [comment]
Currently, we decided to use HTTP to handle sending messages as for our use case the user should receive messages when not authenticated, and by authenticating they'll be able to send messages.
