### ISSUE TITLE
Potential typo/error in parsing socketIO url

### ISSUE THREAD

**Issue by aaronr5** [robtaussig/react-use-websocket#6]
Should the regex line in the code below be this instead ```/^https|wss/.test(url); ``` 
The way it is now ```isSecure``` would be true for urls prefixed by ```ws``` which from my understanding is unsecure and will cause problems if you try to connect to an unsecure websocket server with the ```wss``` prefix rather than ```ws```.
 
https://github.com/robtaussig/react-use-websocket/blob/ba3de50ccdb141655b52b303d486b6adfcdd5355/src/lib/socket-io.js#L5

**Comment by robtaussig** [comment]
Great catch! Fixed and bumped version in https://github.com/robtaussig/react-use-websocket/commit/c897340f2cde6ce5255c2f169c37b769e5603285
