### ISSUE TITLE
readyState not changed when websocket has been closed

### ISSUE THREAD

**Issue by fourteenmeister** [robtaussig/react-use-websocket#63]
https://stackblitz.com/edit/react-5tgwoe?file=index.js

when click on Close socket button onClose event does not fire either and readyState has not changed, 
but in fact the connection is closed

Question: does this hook support a close event from the client side?

**Comment by robtaussig** [comment]
Thank you for catching this! Fixed here: ed5075 for 2.2.0

The issues were somewhat separate:

1) onClose event was not being called for shared websockets for the last subscriber (i.e., if there were three components sharing a websocket, and all three closed, then the first two would get a close event, but the last one would not. In the case of having a single shared websocket, the close event would not fire).
2) As for the readyState not changing, that was a bug I introduced recently when adding logic to prevent the state setter from being called after a component has unmounted, which is only a concern if the websocket closes passively (after the component unmounts).

You can test here:

https://react-ywxbib.stackblitz.io
