### ISSUE TITLE
 Events are fired multiple times when share is true and the useWebSocket hook is used in different components

### ISSUE THREAD

**Issue by fourteenmeister** [robtaussig/react-use-websocket#64]
https://stackblitz.com/edit/react-h845um?file=index.js

onOpen event in this example works twice, although the connection is only one

**Comment by robtaussig** [comment]
This is expected behavior. Sharing a websocket means that each component subscribes to a single websocket -- so one connection but all other behavior occurs as if the websocket is local to each component.
