### ISSUE TITLE
Handle getWsUrl failiure simmilar to WS failiures

### ISSUE THREAD

**Issue by jaecktec** [robtaussig/react-use-websocket#66]
When async URL fetching fails, try to refetch the url in 'retryInterval' time again.

Why:
Using WebSocket token authentication (wsUrl returns a one time token)
Fetching fails for some reason (Like restarting the service, losing internet connection)
It should try to fetch it after 'retryInterval' 

So I can reconnect once the service is up and running again. 

I'd be willing to add this in a PR if you think this is a valid feature

**Comment by robtaussig** [comment]
Ahh, great point! I will implement for next release, or happy to accept a pull request if you need it sooner.

**Comment by robtaussig** [comment]
Had a moment to check in on this, and my reading of it is that this should already be the behavior. The reconnect function calls the same function used to get the url in the start phase, which means it refetch the url in the retryInterval:

```ts
const start = async () => {
  convertedUrl.current = await getUrl(url, optionsCache); //Fetches/refetches url here

  const protectedSetLastMessage = (message: WebSocketEventMap['message']) => {
    if (!expectClose) {
  setLastMessage(message);
    }
  };

  const protectedSetReadyState = (state: ReadyState) => {
    if (!expectClose) {
      setReadyState(prev => ({
        ...prev,
        ...(convertedUrl.current && {[convertedUrl.current]: state}),
      }));
    }
  };

  removeListeners = createOrJoinSocket(
    webSocketRef,
    convertedUrl.current,
    protectedSetReadyState,
    optionsCache,
    protectedSetLastMessage,
    startRef, // Function called for reconnect
    reconnectCount,
  );
};

//Reconnect by removingPrevious listeners and then calls start function
startRef.current = () => {
  if (!expectClose) {
    if (webSocketProxy.current) webSocketProxy.current = null;
    removeListeners?.();
    start();
  }
};

start();
```
Are you seeing different behavior? If so, do you have any thoughts on how to change above logic?

**Comment by jaecktec** [comment]
maybe we should add some tests 🙈
I noticed this behaviour. 
From the code I think there should be a try/catch around the `getUrl` part..

**Comment by robtaussig** [comment]
Tests are never a bad idea. Will close for now and start working on some tests when time frees up. Feel free to re-open if the problem persists.

**Comment by stanleyk** [comment]
The problem actually persists. Any time the `getUrl` async call throws, no reconnect attempts are made. The throw bubbles up and that's it.
