### ISSUE TITLE
reorder useWebSocket return values?

### ISSUE THREAD

**Issue by jEnbuska** [robtaussig/react-use-websocket#7]
```
  const [sendMessage, lastMessage, readyState] = useWebSocket(socketUrl);
```
I would assume first value reflects the state and the second one would be a callback

Examples:
```
const [state, setState] = useState(initialState);
...
const [state, dispatch] = useReducer(...);
```
That's my gut feeling, but I'm not sure if it is a convention 
In this case, there are several states so it's a bit unclear what the value should be

How about?:
```
  const [{data, status}, sendMessage] = useWebSocket(socketUrl);
```

**Comment by robtaussig** [comment]
This is a good suggestion, and in hindsight I probably should have done that from the get-go. For now, I worry about the implications of changing the order as it will break current usage. That said, I plan on bumping to v1 once I've had time to test this in a project I'm working on, and would be more comfortable introducing breaking changes in a major version bump.

**Comment by jsphstls** [comment]
This sounds like a problem that affects adoption more than usage which could limit feedback.

**Comment by robtaussig** [comment]
Looks like there is enough support here that I'll at least have something to point to if anyone asks why I changed the API! Will implement in next release, and likely make it 2.0.0.

**Comment by robtaussig** [comment]
Thanks everyone -- introduced in 2.0.0

1110333
