### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by Chase22** [robtaussig/react-use-websocket#73]
Currently trying to install the library with react 17 give a dependency resolution exception

```
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.8.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"~16.8.0" from react-use-websocket@2.4.0
npm ERR! node_modules/react-use-websocket
npm ERR!   react-use-websocket@"*" from the root project
```
The library looks really nice and i could easily downgrade to 16.8, but supporting react 17 would be nice

**Comment by robtaussig** [comment]
Thank you @Chase22 for your kind words. Pushed and published cca8dba (v2.4.1)

Let me know if you have any issues!
