### ISSUE TITLE
InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by eric-blue** [robtaussig/react-use-websocket#76]
Hey, I wonder if you can help, or see anything that jumps out at you. I've been having this issue for a while and can't seem to source the issue. I've got a hook that consumes your `useWebSocket` hook with a little more going on. I've simplified it for the example but can post a full version if you think it would help. 

`InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.`

The reason why I'm scratching my head at this is, apart from referencing the `sendMessage` method in my hook, I don't actually consume it anywhere. *So I'm not actually sending anything from client to server, only ever the other way around.*

sample code:
```
import { useCallback, useLayoutEffect, useRef, useState } from "react";
import useWebSocket from "react-use-websocket";

export function useSocket({ url, memberId }: { url: string; memberId: string; }) {
  let timeout = useRef<any>();
  const [active, setActive] = useState(true);

  const getSocketUrl = useCallback((): Promise<string> => new Promise((resolve) => {
    setTimeout(() => {
      resolve(url);
    }, 2000);
  }), [url]);

  const didTimeout = useRef(false);

  const options = {
    fromSocketIO: true,
    queryParams: { memberId },
    // filter: socketFilterMessage,
    onMessage: console.log,
    shouldReconnect: () => didTimeout.current === false,
    onClose: console.log,
  };
  
  const { readyState, sendMessage } = useWebSocket(
    getSocketUrl,
    options,
    active
  );

  const handleTimeout = useCallback(() => {
    timeout.current = undefined;
    didTimeout.current = true;
    setActive(false);
    if (typeof window !== undefined) {
      if (window?.confirm("Your connection with our servers has timed out. Please refresh the page.")) {
        location.reload();
      }
    }}, []
  );

  const startCountdown = useCallback((t: number) => {
    clearTimeout(timeout.current);
    timeout.current = setTimeout(() => {
      handleTimeout();
    }, t)}, [handleTimeout]
  );

  useLayoutEffect(() => {
    switch (readyState) {
      case 1:
        startCountdown(1800000);
        break;
      default:
        break;
    }
  }, [readyState]);

  return [readyState, sendMessage, setActive];
}
```

sorry if this isn't the place for this.

**Comment by eric-blue** [comment]
I should mention that this error is seldom recreated locally, and instead, I am seeing it crop up in logs over time to the tune of 118k events from 6k users, largely on chrome, chrome mobile, edge

**Comment by robtaussig** [comment]
Hi @eric-blue,

I remember you:)

Thank you for bringing this to my attention -- socket.io requires a ping/pong system and so the library sets it up on an interval. Instead of using the function that queues up pre-connection messages, it directly calls WebSocket#send. I have fixed the issue and updated the tests. Live now in version 2.5.0. Thank you so much!

https://github.com/robtaussig/react-use-websocket/commit/72498b53c6c9ad39a6e28bd875fa038bdbb2aa27#diff-a7e5c2a6c7cfadd97a13d5a330cfd4ce154072db3484b4b52e2a0202628ca81a

**Comment by eric-blue** [comment]
This is fantastic! I greatly appreciate it 🎆
