### ISSUE TITLE
How to handle Offline status

### ISSUE THREAD

**Issue by gz89** [robtaussig/react-use-websocket#78]
I configured real-time updates using react-use-websocket library.
If a user goes offline, I need to show offline status.
Is there a feature like that?
For example, ReadyState.OFFLINE

**Comment by robtaussig** [comment]
Hi @gz89,

This might be a little out of scope for a websocket library, but you can accomplish this through the online/offline event listeners:

https://stackoverflow.com/questions/189430/detect-the-internet-connection-is-offline

```js
window.addEventListener('online', () => console.log('came online'));
window.addEventListener('offline', () => console.log('came offline'));
```

**Comment by robtaussig** [comment]
If you wanted to turn that into a react-hook, it might look something like this:

```tsx
  const useOnlineStatus = () => {
    const [isOnline, setIsOnline] = useState(window.navigator.onLine);

    useEffect(() => {
      const handleOnline = () => setIsOnline(true);
      const handleOffline = () => setIsOnline(false);

      window.addEventListener('online', handleOnline);
      window.addEventListener('offline', handleOffline);

      return () => {
        window.removeEventListener('online', handleOnline);
        window.removeEventListener('offline', handleOffline);
      };
    }, []);

    return isOnline;
  }
```

**Comment by gz89** [comment]
Thanks for sharing!
