### ISSUE TITLE
SSR broken: window is not defined

### ISSUE THREAD

**Issue by LoganAtCrypto** [robtaussig/react-use-websocket#86]
The error is raised at:
https://github.com/robtaussig/react-use-websocket/blob/17ae9151fd6d36a35e62f1fee3d6e236971276c6/src/lib/constants.ts#L28

Thanks!

**Comment by jacklooi96** [comment]
Having the same issue

**Comment by hectorchanht** [comment]
I downgrade to 2.6.1 to avoid this problem. dev please fix by avoid using window, thanks

**Comment by robtaussig** [comment]
Thanks @LoganAtCrypto , @jacklooi96 , @hectorchanht for the fast report.

Fixed and bumped to 2.7.1

11265c47645d6e226ece817d290bce9e8d3df5ba
