### ISSUE TITLE
Build to release environment, socket connection failed

### ISSUE THREAD

**Issue by vmto** [robtaussig/react-use-websocket#89]
Build to release environment, socket connection failed

```base
"react-use-websocket": "^2.6.1",
"react-native": "0.61.5",
```

**Comment by robtaussig** [comment]
Could you expand on what your issue is? Is there a stack trace that you can share?

**Comment by vmto** [comment]
> 你能扩展一下你的问题是什么吗？是否有可以共享的堆栈跟踪？



> Could you expand on what your issue is? Is there a stack trace that you can share?

I have a screenshot !!!

![01](https://user-images.githubusercontent.com/22423716/121150293-f7db3800-c875-11eb-9b76-04b2e7bbefb9.png)
![02](https://user-images.githubusercontent.com/22423716/121150303-fc075580-c875-11eb-8795-450bbeac4141.png)
![03](https://user-images.githubusercontent.com/22423716/121150315-fe69af80-c875-11eb-8490-7c236392330d.png)
![04](https://user-images.githubusercontent.com/22423716/121150324-00cc0980-c876-11eb-9e67-89213e519489.png)

**Comment by robtaussig** [comment]
Thanks @vmto for setting up the demo. I'm not familiar with Android development, nor snack.expo.io, so I might be missing some nuance, but what do you make of this?

<img width="2560" alt="Screen Shot 2021-06-09 at 9 55 06 AM" src="https://user-images.githubusercontent.com/18265387/121368802-569dc180-c909-11eb-9591-fd755ad4f83c.png">

I changed the ws url to a public service that echoes back any messages sent to it.

Demo here: https://snack.expo.io/e93ZCJMiw

It was difficult for me to use devtools to inspect websocket traffic when using Android mode, because I don't have access to the original ws endpoint and because the messages and console.log's are handled remotely and communicated via http polling. That said, the above test suggests that it can work on Android, no?

**Comment by vmto** [comment]
> Thanks @vmto for setting up the demo. I'm not familiar with Android development, nor snack.expo.io, so I might be missing some nuance, but what do you make of this?
> 
> <img alt="Screen Shot 2021-06-09 at 9 55 06 AM" width="2000" src="https://user-images.githubusercontent.com/18265387/121368802-569dc180-c909-11eb-9591-fd755ad4f83c.png">
> 
> I changed the ws url to a public service that echoes back any messages sent to it.
> 
> Demo here: https://snack.expo.io/e93ZCJMiw
> 
> It was difficult for me to use devtools to inspect websocket traffic when using Android mode, because I don't have access to the original ws endpoint and because the messages and console.log's are handled remotely and communicated via http polling. That said, the above test suggests that it can work on Android, no?



> Thanks @vmto for setting up the demo. I'm not familiar with Android development, nor snack.expo.io, so I might be missing some nuance, but what do you make of this?
> 
> <img alt="Screen Shot 2021-06-09 at 9 55 06 AM" width="2000" src="https://user-images.githubusercontent.com/18265387/121368802-569dc180-c909-11eb-9591-fd755ad4f83c.png">
> 
> I changed the ws url to a public service that echoes back any messages sent to it.
> 
> Demo here: https://snack.expo.io/e93ZCJMiw
> 
> It was difficult for me to use devtools to inspect websocket traffic when using Android mode, because I don't have access to the original ws endpoint and because the messages and console.log's are handled remotely and communicated via http polling. That said, the above test suggests that it can work on Android, no?

Usewebsocket is an excellent socket connection library, especially in the friendly aspect of hooks. I like its API design very much. At present, I can't reproduce the bugs of Android compiled app. I can only capture the screenshots through fiddler.exe agent. I had to use native websocket in my project to meet my needs. I will study use websocket further. Thank you for your time.

**Comment by robtaussig** [comment]
@vmto I appreciate the kind words, and I'm sorry that we couldn't get to the bottom of this. I will keep this issue open for another week to see if anyone else reports the same issue.
